### ISSUE TITLE
Dockerize truffle/solidity project

### ISSUE THREAD

**Issue by amirhabibzadeh** [treejer/contract#22]
We need to create a docker-compose file, so everyone can run this project with docker and start testing and developing easily.

**Comment by RISHIKESHAVAN** [comment]
Hi @amirhabibzadeh, I would like to work on this.

**Comment by amirhabibzadeh** [comment]
Good news @RISHIKESHAVAN 
Ask me anything you need, We are waiting for the pull request.

**Comment by RISHIKESHAVAN** [comment]
@amirhabibzadeh can you please assign this issue to me?
